version: "3"

services:

  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    command: python ./server/server.py
    ports:
      - 3333:3333
    depends_on:
      - mongo
      - auth
    restart: always

  auth:
    build:
      context: .
      dockerfile: auth/Dockerfile
    command: python ./auth/auth.py

    ports:
      - 2222:2222
      - 6066:6066
    depends_on:
      - rabbitmq
    restart: always

  push:
    build:
      context: .
      dockerfile: push/Dockerfile
    command: python ./push/push.py
    ports:
      - 2345:2345
    depends_on:
      - rabbitmq
    restart: always

  mongo:
    image: mongo
    ports:
      - "27017:27017"

  rabbitmq:
    image: rabbitmq:3.6.6-management
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=user
    ports:
      - "5672:5672"
      - "15672:15672"

