# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: validation.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='validation.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x10validation.proto\"2\n\x11ValidationRequest\x12\r\n\x05token\x18\x01 \x01(\t\x12\x0e\n\x06\x61\x63tion\x18\x02 \x01(\t\"&\n\x12ValidationResponse\x12\x10\n\x08is_valid\x18\x01 \x01(\x08\x32\x42\n\tValidator\x12\x35\n\x08Validate\x12\x12.ValidationRequest\x1a\x13.ValidationResponse\"\x00\x62\x06proto3'
)




_VALIDATIONREQUEST = _descriptor.Descriptor(
  name='ValidationRequest',
  full_name='ValidationRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='token', full_name='ValidationRequest.token', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='action', full_name='ValidationRequest.action', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=70,
)


_VALIDATIONRESPONSE = _descriptor.Descriptor(
  name='ValidationResponse',
  full_name='ValidationResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='is_valid', full_name='ValidationResponse.is_valid', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=72,
  serialized_end=110,
)

DESCRIPTOR.message_types_by_name['ValidationRequest'] = _VALIDATIONREQUEST
DESCRIPTOR.message_types_by_name['ValidationResponse'] = _VALIDATIONRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ValidationRequest = _reflection.GeneratedProtocolMessageType('ValidationRequest', (_message.Message,), {
  'DESCRIPTOR' : _VALIDATIONREQUEST,
  '__module__' : 'validation_pb2'
  # @@protoc_insertion_point(class_scope:ValidationRequest)
  })
_sym_db.RegisterMessage(ValidationRequest)

ValidationResponse = _reflection.GeneratedProtocolMessageType('ValidationResponse', (_message.Message,), {
  'DESCRIPTOR' : _VALIDATIONRESPONSE,
  '__module__' : 'validation_pb2'
  # @@protoc_insertion_point(class_scope:ValidationResponse)
  })
_sym_db.RegisterMessage(ValidationResponse)



_VALIDATOR = _descriptor.ServiceDescriptor(
  name='Validator',
  full_name='Validator',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=112,
  serialized_end=178,
  methods=[
  _descriptor.MethodDescriptor(
    name='Validate',
    full_name='Validator.Validate',
    index=0,
    containing_service=None,
    input_type=_VALIDATIONREQUEST,
    output_type=_VALIDATIONRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_VALIDATOR)

DESCRIPTOR.services_by_name['Validator'] = _VALIDATOR

# @@protoc_insertion_point(module_scope)
